### ISSUE TITLE
Remove "Special" formatting from web app

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#437] opened 2017-01-28 07:06 UTC
We received feedback from one of our customers: In our native app(s) formatting e.g. font sizes and font families are removed clearly. In our web app it's not removed and therefore an inconsistent layout/view between app and web app. Formatting should also be "removed" or replaced in the web app.

**Comment by sven15** [comment] 2017-01-28 09:01
Duplicate of https://github.com/Integreat/cms/issues/413

**Closed by sven15** 2017-01-28 09:01 UTC
Labels: area:UI, info:help wanted, prio:medium
