### ISSUE TITLE
SuperAdmin should be able to delete posts/media permanently

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#505] opened 2017-04-04 16:27 UTC
Due to a clean structure and instance it should be possible for a superadmin to delete pages/translations whatever completely from the system. Currently we have an issue in our german template that frech is disabled but pages are still in the bin. This is why Farsi pages are sometimes still depended from the delelted French pages.

**Comment by sven15** [comment] 2017-04-07 18:15
We cannot delete posts. We can only hide them.

**Comment by sven15** [comment] 2017-04-16 15:41
Create a link and post meta "permanently_hide_post" or similar. If this is set, the post should not show up in trash bin.

**Comment by svenseeberg** [comment] 2017-06-25 14:52
Done with #534, duplicate of #531

**Closed by svenseeberg** 2017-06-25 14:52 UTC
Labels: area:UI, ease:medium, prio:medium, type:enhancement
