### ISSUE TITLE
Automatic Translation also on Pages marked as "Draft"

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#315] opened 2016-02-17 17:16 UTC
The Automatic Translation may also appear on pages which are currently in "draft"-mode.

**Comment by sven15** [comment] 2016-02-19 13:56
* Is WPML working with post_status='rvy-pending' ?
* register_status for rvy-pending ?
* maybe adding the button to the revisionary edit and adding the rvy-pending status in the translation will work.

**Comment by sven15** [comment] 2017-03-25 18:53
This is actually something we would want to have (beyond nice to have).

**Comment by sven15** [comment] 2017-04-02 09:09
worded differently but duplicate of #354

**Closed by sven15** 2017-04-02 09:09 UTC
Labels: area:Functional, ease:medium, prio:low
