### ISSUE TITLE
Remove/Undisplay "Sprache"-Widget from Events

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#485] opened 2017-03-27 14:54 UTC
To simplify the event creation process we should remove the "Sprache"-Widget where you can manage the Translations from the event detail page. We should rather enable the auto-translation for EVERY event which is saved. Save-Button = Auto-Translation is created.

This topic occured because we currently build the cms documentation and there is nothing to explain regarding the Sprachen-Widget for Events because it's a waste of time to insert translations manually and duplication should be avoided directly if auto-translation is a simple way.

**Comment by sven15** [comment] 2017-03-27 16:04
reopened #438 and added this.

**Comment by sven15** [comment] 2017-03-27 16:04
To simplify the event creation process we should remove the "Sprache"-Widget where you can manage the Translations from the event detail page. We should rather enable the auto-translation for EVERY event which is saved. Save-Button = Auto-Translation is created.

This topic occured because we currently build the cms documentation and there is nothing to explain regarding the Sprachen-Widget for Events because it's a waste of time to insert translations manually and duplication should be avoided directly if auto-translation is a simple way.

**Comment by sven15** [comment] 2017-03-27 16:25
Confused some browser tabs

**Comment by sven15** [comment] 2017-03-27 16:34
duplicate of #406

**Closed by sven15** 2017-03-27 16:34 UTC
Labels: area:UI, ease:medium
