### ISSUE TITLE
Statistics menu point not available anymore for Verwalter

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#882] opened 2018-11-21 15:33 UTC
Three cities already reported us that the menu point for statistics is not accessible/visible anymore in the cms system, but it was a feew weeks ago.

Can we reproduce that or find the cause?

**Comment by dkehne** [comment] 2018-11-28 08:46
Could reproduce it also with LK Schwäbisch Hall.

**Comment by timoludwig** [comment] 2018-11-28 16:11
Duplicate of #836 and #845. Short-term solution is to save the WP Piwik settings.
For a long-term solution we need more info, e.g. the approximate date when the error occurred in each of the cities.

**Comment by svenseeberg** [comment] 2019-01-30 11:59
This was a settings problem in the User Role Editor.

**Closed by svenseeberg** 2019-01-30 11:59 UTC
Labels: prio:high
