### ISSUE TITLE
Adding users to an instance (network site) is not possible via network settings

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#426] opened 2016-11-08 19:34 UTC
If one tries to add an user to a network site via "Netwerkverwaltung" > "websites" error message "Ungültige Website-ID." appears.

**Comment by dkehne** [comment] 2016-11-09 00:11
The same error comes when adding a new instance or deleting an instance. If you do the same without cache in "private mode" e.g. in mozilla, it all works. so it seems to be a cache problem.

**Comment by sven15** [comment] 2017-03-24 14:44
Never had this problem. Can someone confirm that this still persists? Otherwise please close this issue.

**Comment by sven15** [comment] 2017-03-25 14:59
Confirmed. This is a core functionality. Should be fixed upstream ....
`host/wordpress/wp-admin/network/site-users.php?action=adduser&lang=de&redirectlang=1`

**Comment by sven15** [comment] 2017-03-25 19:05
https://premium.wpmudev.org/forums/topic/error-when-trying-to-add-user-to-site

**Comment by benginoe** [comment] 2017-03-27 18:50
I take care of it.

**Comment by sven15** [comment] 2017-03-28 20:31
This is probably directly connected to #494 #495 and also to #496

**Comment by sven15** [comment] 2017-03-29 18:30
Solved together with #494

**Closed by sven15** 2017-03-29 18:30 UTC
Labels: area:Functional, prio:low, type:bug
